name: flutter_native_badge_foundation
description: iOS and macOS implementation of the flutter_native_badge plugin.
  Wraps the native APIs for iOS and macOS to set the badge count on the app icon.
repository: https://github.com/isaacadariku/flutter_native_badge/tree/main/flutter_native_badge_foundation
issue_tracker: https://github.com/isaacadariku/flutter_native_badge/issues
version: 1.0.4+dev

environment:
  sdk: ">=3.3.4 <4.0.0"
  flutter: ">=3.19.6"

flutter:
  plugin:
    implements: flutter_native_badge
    platforms:
      ios:
        pluginClass: FlutterNativeBadgePlugin
        dartPluginClass: FlutterNativeBadgeFoundation
      macos:
        pluginClass: FlutterNativeBadgePlugin
        dartPluginClass: FlutterNativeBadgeFoundation

dependencies:
  flutter:
    sdk: flutter
  flutter_native_badge_platform_interface: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: ^18.0.0

scripts: derry.yaml
