// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


private class FlutterNativeBadgePigeonCodecReader: FlutterStandardReader {
}

private class FlutterNativeBadgePigeonCodecWriter: FlutterStandardWriter {
}

private class FlutterNativeBadgePigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return FlutterNativeBadgePigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return FlutterNativeBadgePigeonCodecWriter(data: data)
  }
}

class FlutterNativeBadgePigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = FlutterNativeBadgePigeonCodec(readerWriter: FlutterNativeBadgePigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol FlutterNativeBadgeApi {
  func requestPermission(completion: @escaping (Result<Void, Error>) -> Void)
  func getBadgeCount() throws -> Int64
  func setBadgeCount(count: Int64) throws
  func clearBadgeCount() throws
  func showRedDot() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class FlutterNativeBadgeApiSetup {
  static var codec: FlutterStandardMessageCodec { FlutterNativeBadgePigeonCodec.shared }
  /// Sets up an instance of `FlutterNativeBadgeApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: FlutterNativeBadgeApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let requestPermissionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_native_badge_foundation.FlutterNativeBadgeApi.requestPermission\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestPermissionChannel.setMessageHandler { _, reply in
        api.requestPermission { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestPermissionChannel.setMessageHandler(nil)
    }
    let getBadgeCountChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_native_badge_foundation.FlutterNativeBadgeApi.getBadgeCount\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getBadgeCountChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getBadgeCount()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getBadgeCountChannel.setMessageHandler(nil)
    }
    let setBadgeCountChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_native_badge_foundation.FlutterNativeBadgeApi.setBadgeCount\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setBadgeCountChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let countArg = args[0] as! Int64
        do {
          try api.setBadgeCount(count: countArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setBadgeCountChannel.setMessageHandler(nil)
    }
    let clearBadgeCountChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_native_badge_foundation.FlutterNativeBadgeApi.clearBadgeCount\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      clearBadgeCountChannel.setMessageHandler { _, reply in
        do {
          try api.clearBadgeCount()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      clearBadgeCountChannel.setMessageHandler(nil)
    }
    let showRedDotChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_native_badge_foundation.FlutterNativeBadgeApi.showRedDot\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      showRedDotChannel.setMessageHandler { _, reply in
        do {
          try api.showRedDot()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      showRedDotChannel.setMessageHandler(nil)
    }
  }
}
